# ============================================================
# LifeFlow — Production Dockerfile
# Multi-stage build using Next.js standalone output
# ============================================================
#
# Build:
#   docker build -t lifeflow .
#
# Run:
#   docker run -p 3000:3000 \
#     -e MONGODB_URI="mongodb+srv://..." \
#     -e SESSION_SECRET="..." \
#     -e SCHEDULER_SECRET="..." \
#     lifeflow
#
# The image does NOT contain any secrets — all configuration
# is supplied at runtime via environment variables.
# ============================================================

# ── Stage 1: deps ─────────────────────────────────────────────────────────────
# Install production + dev dependencies needed for the build.
# We separate this stage so the layer is cached when only source changes.
FROM node:20-alpine AS deps

# Install libc compatibility for native modules (bcrypt, etc.)
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy only package manifests first — maximises layer cache hits
COPY package.json package-lock.json* ./

# Install ALL dependencies (dev deps needed for build step)
RUN npm ci --frozen-lockfile

# ── Stage 2: builder ──────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy application source
COPY . .

# Build-time environment variables
# These are only used during `next build` — they must be set as build args
# for NEXT_PUBLIC_* vars if you need them baked in at build time.
# All server-side secrets (MONGODB_URI, SESSION_SECRET, etc.) are supplied
# at runtime — they are NOT needed during the build.
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Build the Next.js application
# output: 'standalone' (set in next.config.ts) produces .next/standalone
RUN npm run build

# ── Stage 3: runner ───────────────────────────────────────────────────────────
# Minimal production image — only the standalone output and public assets.
FROM node:20-alpine AS runner

RUN apk add --no-cache libc6-compat

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Default port — override with PORT env var if needed
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy the standalone build output
# .next/standalone contains a minimal server.js and all required modules
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static assets (CSS, JS chunks, images)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Copy public directory (favicon, robots.txt, etc.)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Switch to non-root user
USER nextjs

# Expose the application port
EXPOSE 3000

# Docker health check — uses the /api/health endpoint
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/health || exit 1

# Start the production server
# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
